language: python
python:
  - 2.6
  - 2.7
  - "2.7_with_system_site_packages"
before_install:
  # If system_site_packages are available, we install PyQt4 and run the UI tests.
  - if [[ $TRAVIS_PYTHON_VERSION == *_with_system_site_packages ]]; then source .travis_before_install; fi
install:
  - pip install -U nose
  - pip install -U unittest2
  # 'envisage' should work with the current 'traits' master
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - pip install apptools
  - python setup.py develop
script:
  - if [[ $TRAVIS_PYTHON_VERSION == *_with_system_site_packages ]]; then nosetests envisage; else nosetests envisage/tests; fi
notifications:
  email:
    - travis-ci@enthought.com
