language: python
sudo: false
python:
  - 2.6
  - 2.7_with_system_site_packages
addons:
  apt:
    packages:
    - python-qt4
    - python-setuptools
    - ccache
env:
  - ETS_TOOLKIT=qt4
cache:
  - ccache
  - pip
before_install:
  - ccache -s
  - pip install --upgrade pip virtualenv
  - pip install -I setuptools
  - virtualenv my_env --with-system-site-packages
  - if [[ TRAVIS_PYTHON_VERSION != '2.6 ]]; then source /my_env/bin/activate; fi
  - pip --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r travis-ci-requirements.txt
  - python setup.py develop
script:
  - coverage run -m nose.core envisage -v
after_success:
  - pip install codecov
  - codecov